name: Feature request
description: Suggest an improvement
labels: ["enhancement"]
body:
  - type: textarea
    id: feature
    attributes:
      label: What would you like?
    validations:
      required: true
  - type: textarea
    id: context
    attributes:
      label: Context
      description: Your intercom model, use case, or anything else that helps.
